### ISSUE TITLE
Private repositories

### ISSUE THREAD

**Issue by robottomw** [saracen/lfscache#1]
Loving this tool. We'd like to try using it with our private repositories but it seems to fail with a 403 error when we use it with our HTTPS credentials and an personal access token which works when we git clone directly (i.e. without using lfscache as a proxy).

Can you tell us how to use lfscache to proxy private LFS repositories on github?

Using a github.com personal access token in place of <password>, we run the lfscache server with:

```
lfscache_0.1.0_darwin_amd64/lfscache --url <username>:<password>@github.com/<org>/<repo>.git/info/lfs --directory /tmp/lfstest --http-addr=:9876
```

Configure our git lfs url:

```
git config --global --replace-all lfs.url "http://localhost:9876/"
```

Then attempt to clone with:

```
git clone git@github.com:<org>/<repo>.git
```

Our lfscache server outputs:

```
level=error ts=2019-01-03T15:32:37.504463Z event=proxying request=https://<username>:<password>@github.com/<org>/<repo>.git/info/lfs/objects/batch err="remote server responded with 403 status code"
```

However this following command seems to work indicating that the issue lies with lfscache:

```
git clone  https://<username>:<password>@github.com/<org>/<repo>.git
```

Thanks,
Tom

**Comment by saracen** [comment]
Hey @robottomw 

Sorry for the delay in getting back to you.

Does it improve matters If the URL you pass to lfscache excludes the username/password, for example:
```
lfscache_0.1.0_darwin_amd64/lfscache --url https://github.com/<org>/<repo>.git/info/lfs --directory /tmp/lfstest --http-addr=:9876
```
lfscache wasn't intended to perform the authentication on behalf of clients, but instead pass through the credentials provided by the client.

Does your git client get prompted for a username and password?

**Comment by saracen** [comment]
@robottomw 

Are you still having issues with this?

**Comment by robottomw** [comment]
Thanks Aaran,

I think we can close this for now. It works on my machine with login
prompt.
