### ISSUE TITLE
unknown field 'ErrorHandler' 

### ISSUE THREAD

**Issue by ozkolonur** [saracen/lfscache#2]
I am trying build & modify this project. I am getting an build error, I guess it is related with go version but i am not sure.

I appreciate if you can give me a hint about error. 
Thanks for this important piece of project.

vagrant@devbox:~/go$ go get github.com/saracen/lfscache

github.com/saracen/lfscache/server
src/github.com/saracen/lfscache/server/server.go:170:64: unknown field 'ErrorHandler' in struct literal of type httputil.ReverseProxy
vagrant@devbox:~/go$ go version
go version go1.10.4 linux/amd64

**Comment by saracen** [comment]
Hey,

Yeah, the standard library's http `ReverseProxy` only supports `ErrorHandler` with version >=1.11 (https://golang.org/doc/go1.11#net/http/httputil).

Are you able to upgrade? 

Alternatively, you _could_ remove the mentions of ErrorHandler here: https://github.com/saracen/lfscache/blob/master/server/server.go#L166-L170 but if there's any issues with the connection to your LFS server they'll be difficult to debug without the error notifications :(

There's also binaries available on the releases page: https://github.com/saracen/lfscache/releases

**Comment by ozkolonur** [comment]
Thanks updating go 1.11 worked fine.
I can also confirm it is working for bitbucket  5.11.1 as well.

**Comment by saracen** [comment]
Thanks for confirming that it works on Bitbucket. Do let me know if you have any other issues or think something can be improved!
