### ISSUE TITLE
http to https on different server

### ISSUE THREAD

**Issue by svsintel** [saracen/lfscache#4]
I am have a git repo that uses lfs.  The LFS server is a totally different machine.

github:  git@github.com/.......

lfs https://machine.domain:9999/artifactory/mystore

it was started with
/lfscache --url https://machine.domain:1339/artifactory/git_lfs_store/info/lfs --directory /srv/docker-helper/shares/cache/gitcache/lfs --http-addr=172.17.0.1:9876

The error
level=error ts=2019-12-12T00:41:04.943901096Z event=proxying request=https://machine.domain:1339/artifactory/git_lfs_store/info/lfs/objects/batch err="tls: first record does not look like a TLS handshake"

But I do not see network traffic going to the lfs-store machine.

Q1>  in the url , do I need .../info/lfs ?  I think it might work better without the added /info/lfs

Q2>  looking at the server code I see 
'''
http: req.TLS == nil
'''
the input request is http but the outgoing needs TLS
it would look like this    clone-machine : http <->  lfsproxy : https <-> lfs-store

**Comment by svsintel** [comment]
I have worked around all the issues until auth.   in server.go:batch, I get a 401 return and I want to pass that back to the git-lfs.  
How do I pass the auth request back?

**Comment by saracen** [comment]
Hey,

It should just be a case of using:
```
lfscache --url https://machine.domain:1339/artifactory/git_lfs_store/info/lfs --directory /srv/docker-helper/shares/cache/gitcache/lfs --http-addr=172.17.0.1:9876
```
...and then in your repository directory, ensure that the proxy server will be used:
```
git config lfs.url http://172.17.0.1:9876/

# confirm with
git lfs env | grep Endpoint
```

The upstream server running on HTTPS should not be an issue. We've seen several successful deployments where this has been the case (Github and Bitbucket both have HTTPS endpoints).

If the upstream server requires authentication, that requirement should be passed through without modification, usually resulting in git lfs prompting for a username and password.

`/info/lfs` is server dependent, it might be that Artifactory does not require this. Have you tried using `--url https://machine.domain:1339/artifactory/git_lfs_store` (without the info/lfs suffix)?

**Comment by saracen** [comment]
@svsintel Is this still an issue?

**Comment by svsintel** [comment]
Still having issues with lfs and artifactory, but the authentication issues is fixed.
