### ISSUE TITLE
TLS option?

### ISSUE THREAD

**Issue by comerford** [saracen/lfscache#6]
Wondering if there is any appetite for TLS support on the cache? I have worked around this myself using a load balancer for my use case, but since net/http is already in there, I did a quick test of just having it as a boolean config (with a static path) and using the built in listen with TLS, see here:

https://github.com/comerford/lfscache/blob/master/main.go#L61

Basic test worked, would just need some sane way to specify the cert paths in the options rather than static config, but will leave that to someone with more actual Go experience.

P.S. Super useful little program - thanks!

**Comment by saracen** [comment]
@comerford v0.1.3 now contains a `-https-addr`, `-tls-cert` and `-tls-key` option to configure HTTPS.

Let me know if you experience any trouble with it, and thank you for the feature request!
