### ISSUE TITLE
panic: runtime error: index out of range [-9223372036854775808]

### ISSUE THREAD

**Issue by llob** [saracen/lfscache#8]
We have an lfs repo with 60.000+ files. I am seeing an issue where some files are correctly downloaded and cached, but the program crashes after some files.
Output looks like this:

level=info ts=2020-06-23T12:06:03.1992193Z event=fetched oid=9230f90f3b3f461400dd00fdb3c2257c22332466bb9ad0c8476e7a23d46c458a took=567.9984ms downloaded=45180/45180 rate="852 KB/s"
level=info ts=2020-06-23T12:06:03.2002201Z event=served oid=9230f90f3b3f461400dd00fdb3c2257c22332466bb9ad0c8476e7a23d46c458a source=fresh took=570.0011ms size=45180 rate="79 KB/s"
level=info ts=2020-06-23T12:06:03.21022Z event=serving oid=63b5bca91e6758cd576111976ed5c69887e2a57b074db0aca53a5843ebecc9ff source=fresh
level=info ts=2020-06-23T12:06:03.21022Z event=fetching oid=63b5bca91e6758cd576111976ed5c69887e2a57b074db0aca53a5843ebecc9ff
panic: runtime error: index out of range [-9223372036854775808]

goroutine 130 [running]:
github.com/git-lfs/git-lfs/tools/humanize.FormatByteRate(0xb07c, 0x0, 0x9f61a0, 0x0)
        /home/travis/gopath/pkg/mod/github.com/git-lfs/git-lfs@v2.5.2+incompatible/tools/humanize/humanize.go:160 +0x318
github.com/saracen/lfscache/server.(*Server).fetch.func1(0xc0001926f0, 0xc0008efee0, 0xc0000d4180, 0xc000188130, 0x40, 0xbfb499eacc970048, 0x40e92108d, 0x9f61a0, 0xb07c, 0xc0008effd0)
        /home/travis/gopath/src/github.com/saracen/lfscache/server/server.go:405 +0x7d
github.com/saracen/lfscache/server.(*Server).fetch(0xc0000d4180, 0x272f0240, 0xc0001925a0, 0xc000188130, 0x40, 0xc0000a4000, 0x50, 0xb07c, 0xc000192540, 0x0, ...)
        /home/travis/gopath/src/github.com/saracen/lfscache/server/server.go:445 +0x584
created by github.com/saracen/lfscache/server.(*Server).serve
        /home/travis/gopath/src/github.com/saracen/lfscache/server/server.go:354 +0x6b3

Update 1:
Version is: 0.1.3, commit 848d795dde4930919bec1f0b9f7b6061863f3a33, built at 2020-06-20T14:23:14Z

**Comment by saracen** [comment]
@llob Thank you for reporting this.

Can you try and see if `0.1.4` works for you?
